runtime: python38

instance_class: B1

service: question-bot

manual_scaling:
  instances: 1

entrypoint: python3 main.py

env_variables:
  SHEET_ID: '1bNhH84cUS-g8Pej72EkFD8_f30v7Y_43hDoTrDOI0-I'
  PROJECT_ID: '120836897182'
  SECRET_ID: 'question-bot-secret'