runtime: python38

instance_class: B1

service: question-bot

manual_scaling:
  instances: 1

entrypoint: python3 main.py

env_variables:
  SHEET_ID: '1t7vdvHQBdbwpPqBf3DWHLeCve2hV9HUut3xJONkx3ZY'
  PROJECT_ID: '960772171792'
  SECRET_ID: 'question-of-the-day-bot-token'